insert into customer_types (id, caption) values (1, 'Residential');
insert into customer_types (id, caption) values (2, 'Medium Business');
insert into customer_types (id, caption) values (3, 'Enterprise');

insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (1, 'Dr', 'Shelden', 'XLTN', 'Abrahams', 'BRHMS', '2019-01-17', 3);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (2, 'Dr', 'Murry', 'MR', 'Elcombe', 'ELKMB', '2019-10-09', 2);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (3, 'Dr', 'Bartolomeo', 'BRTLM', 'Blackmoor', 'BLKMR', '2019-03-05', 1);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (4, 'Mr', 'Marget', 'MRJT', 'Abrahams', 'ABRHMS', '2019-04-26', 3);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (5, 'Mr', 'Mel', 'ML', 'Boggas', 'BKS', '2019-11-23', 2);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (6, 'Mrs', 'Gard', 'KRT', 'Sully', 'SL', '2019-02-26', 1);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (7, 'Dr', 'Brier', 'BRR', 'Feathersby', 'F0RSB', '2019-03-13', 3);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (8, 'Dr', 'Svend', 'SFNT', 'Caldeiro', 'KLTR', '2019-04-26', 2);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (9, 'Dr', 'Xylina', 'SLN', 'Pieracci', 'PRKS', '2019-03-04', 1);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (10, 'Mrs', 'Arin', 'ARN', 'Shorland', 'XRLNT', '2019-03-11', 3);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (11, 'Mrs', 'Ruthann', 'R0N', 'Barca', 'BRK', '2019-10-24', 2);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (12, 'Mr', 'Shadow', 'XT', 'Dumphy', 'TMF', '2019-10-23', 3);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (13, 'Rev', 'Alix', 'ALKS', 'Matthewman', 'MTMN', '2019-11-23', 1);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (14, 'Mrs', 'Clem', 'KLM', 'Connolly', 'KNL', '2019-05-19', 2);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (15, 'Rev', 'Dallas', 'TLS', 'Leathe', 'L0', '2019-07-31', 3);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (16, 'Mr', 'Alfred', 'ALFRT', 'Schoenfisch', 'SKNFSK', '2019-02-17', 1);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (17, 'Ms', 'Van', 'FN', 'Toolin', 'TLN', '2019-11-03', 2);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (18, 'Mrs', 'Cathi', 'K0', 'Jarrell', 'JRL', '2019-11-14', 3);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (19, 'Dr', 'Guglielma', 'KKLLM', 'Loyns', 'LNS', '2019-06-17', 1);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (20, 'Mrs', 'Whittaker', 'WTKR', 'Chrippes', 'XRPS', '2019-01-12', 2);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (21, 'Rev', 'Claiborn', 'KLBRN', 'Burles', 'BRLS', '2019-08-15', 3);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (22, 'Mr', 'Angie', 'ANJ', 'Pruvost', 'PRFST', '2019-03-10', 1);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (23, 'Ms', 'Shannon', 'XNN', 'Tommasetti', 'TMST', '2019-05-08', 2);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (24, 'Mrs', 'Eudora', 'ETR', 'Hanalan', 'HNLN', '2019-03-11', 3);
insert into customers (id, title, first_name, first_name_metaphone, last_name, last_name_metaphone, modified_when, customer_types) values (25, 'Ms', 'Forbes', 'FRBS', 'Benedicte', 'BNTKT', '2019-08-28', 1);
