#spring:
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: qwerty
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
#      hibernate.temp.use_jdbc_metadata_defaults: false
#
#  profiles:
#    active: default
#
#server:
#  port: 8083
